apiVersion: v1
kind: Secret
metadata:
  name: blog-api-secret
  labels:
    app: blog-api
type: Opaque
stringData:
  # Database
  db-username: "my-db-username"
  db-password: "my-super-secret-db-password"

  # OAuth2
  oauth-google-client-id: "your-google-client-id"
  oauth-google-client-secret: ""

  # ReCAPTCHA
  google-recaptcha-secret-v2: "your-recaptcha-v2-secret-key"
  google-recaptcha-secret-v3: "your-recaptcha-v3-secret-key"

  # JWT
  jwt-secret: "your-jwt-secret-key"

  # Mailgun
  mailgun-username: "your-mailgun-username"
  mailgun-password: "your-mailgun-password"