apiVersion: v1
kind: Service
metadata:
  name: blog-api-service
  labels:
    app: blog-api
spec:
  # 외부 노출 없이 클러스터 내부에서만 접근 가능하도록 설정 (보안 강화)
  type: ClusterIP
  selector:
    # 이 라벨을 가진 Pod(백엔드)로 트래픽을 전달합니다.
    app: blog-api
  ports:
    - protocol: TCP
      port: 8080        # K8S 내부망에서 서비스가 수신할 포트
      targetPort: 8080  # 실제 Spring Boot 컨테이너가 열어둔 포트