import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Footer } from './_component/footer';
import Header from './_component/header';
import Sidebar from './_component/sidebar';
import TableOfContents from './_component/tableOfContents';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageHeadings: { id: string; text: string; level: number }[] = [];

  return (
    <html lang="en">
      <body className="grid h-screen grid-rows-[auto_1fr_auto]">
        <Header />
        <div className="grid grid-cols-[auto_1fr_auto] overflow-hidden">
          <Sidebar />
          <main className="overflow-auto p-4">
            <div className="flex-grow p-4">{children}</div>
          </main>
          <TableOfContents headings={pageHeadings}></TableOfContents>
        </div>
        <Footer />
      </body>
    </html>
  );
}
