spring:
  application:
    name: blog-batch
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: never # The production database is managed using migration tools like Flyway.
    job:
      enabled: true # Prevent all jobs from starting automatically on startup.

common:
  mail:
    mailgun:
      api-key: ${MAILGUN_API_KEY}
      domain: ${MAILGUN_DOMAIN}
      from-address: "Contentria <no-reply@${MAILGUN_DOMAIN}>"
