apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-frontend-web
data:
  NEXT_PUBLIC_EXTERNAL_API_BASE_URL: "https://dev.contentria.com/api"
  NEXT_PUBLIC_GOOGLE_REDIRECT_URI: "https://dev.contentria.com/api/auth/google/callback"
