export const ERROR_CODES = {
  // Common
  INTERNAL_SERVER_ERROR: 'C0000',
  INVALID_INPUT_VALUE: 'C0001',
  METHOD_NOT_ALLOWED: 'C0002',
  CLIENT_IP_NOT_FOUND: 'C0003',
  RECAPTCHA_TOKEN_MISSING: 'C0004',
  RECAPTCHA_VERIFICATION_FAILED: 'C0005',
  RECAPTCHA_V3_ACTION_MISMATCH: 'C0006',

  // Sign Up
  INVALID_VERIFICATION_CODE: 'SU0000',
  EMAIL_DUPLICATION: 'SU0001',

  // Auth
  UNEXPECTED_AUTHENTICATION_PRINCIPAL: 'AU0000',
  OIDC_INVALID_PRINCIPAL: 'AU0001',
  OIDC_MISSING_EMAIL: 'AU0002',
  OIDC_POST_PROCESSING_FAILED: 'AU0003',
  REFRESH_TOKEN_NOT_FOUND: 'AU0004',
  REFRESH_TOKEN_EXPIRED: 'AU0005',
  AUTHENTICATED_USER_NOT_FOUND: 'AU0006',
  AUTHENTICATION_REQUIRED: 'AU0007',
  AUTHORIZATION_FAILED: 'AU0008',
  INVALID_CREDENTIALS: 'AU0009',

  // User
  USER_NOT_FOUND: 'US0000',
} as const;
