server:
  port: 8080
  servlet:
    context-path: /api
logging:
  level:
    root: INFO
    com.giffing.bucket4j: INFO
    org.springframework.security.web: INFO
spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # 운영 환경에서는 validate 설정 필요. (Flyway 또는 Liquibase 같은 데이터베이스 마이그레이션 도구도 고려)
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider # Cache Provider가 하나일 경우 생략 가능하지만, 명시성을 위해 기입
    cache-names:
      - rateLimiting
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
bucket4j:
  enabled: true
  filters:
    - id: rateLimitingFilter
      cache-name: rateLimiting
      url: "/api/auth/.*"
      rate-limits:
        - cache-key: "@ipResolver.getClientIp(#root)"
          post-execute-condition: getStatus() eq 200
          numTokens: 1 # The number of tokens that should be consumed
          bandwidths:
            - capacity: 10
              initial-capacity: 10
              time: 1
              unit: minutes
              refill-speed: interval
app:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: 15m   # access token 만료 시간: 15분
      refresh-token-expiration: 7d   # refresh token 만료 시간: 7일
    cookie:
      access-token-name: "access_token"
      refresh-token-name: "refresh_token"
      access-token-path: "/"
      refresh-token-path: "/api/auth"
    oidc:
      success-redirect-url: http://localhost:3000/dashboard
    verification-code:
      ttl-minutes: 10
      length: 6
      redis-key-prefix: "verification_code:email:"
    recaptcha:
      v2-secret-key: ${GOOGLE_RECAPTCHA_V2_SECRET_KEY}
      v3-secret-key: ${GOOGLE_RECAPTCHA_V3_SECRET_KEY}
      score-threshold: 1.0 # 이 점수 이상이어야 통과로 간주
      site-verify-url: "https://www.google.com/recaptcha/api/siteverify"
      expected-hostname: "localhost"
      expected-actions:
        signup_initiate: "signup_initiate"
        login: "login"
  cors:
    allowed-origins:
      - http://localhost:3000
common:
  mail:
    mailgun:
      api-key: ${MAILGUN_API_KEY}
      domain: ${MAILGUN_DOMAIN}
      from-address: "no-reply@${MAILGUN_DOMAIN}"
