server:
  port: 8080
  servlet:
    context-path: /api


spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # 운영 환경에서는 validate 설정 필요. (Flyway 또는 Liquibase 같은 데이터베이스 마이그레이션 도구도 고려)
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

app:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration: 15m   # access token 만료 시간: 15분
      refresh-token-expiration: 7d   # refresh token 만료 시간: 7일
    cookie:
      access-token-name: "access_token"
      refresh-token-name: "refresh_token"
      access-token-path: "/"
      refresh-token-path: "/api/auth"
    oidc:
      success-redirect-url: http://localhost:3000/dashboard
    verification-code:
      ttl-minutes: 10
      length: 6
      redis-key-prefix: "verification_code:email:"
    recaptcha:
      v2-secret-key: ${RECAPTCHA_V2_SECRET_KEY}
      v3-secret-key: ${RECAPTCHA_V3_SECRET_KEY}
      score-threshold: 1.0 # 이 점수 이상이어야 통과로 간주
      site-verify-url: "https://www.google.com/recaptcha/api/siteverify"
      expected-hostname: "localhost"
      expected-actions:
        signup_initiate: "signup_initiate"
        login: "login"
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    root: info

bucket4j:
  enabled: true
  filter-config-caching-enabled: true
  filter-config-cache-name: filterConfigCache
  methods:
    - name: default
      cache-name: buckets
      rate-limit:
        cache-key: 1
        bandwidths:
          - capacity: 1
            refill-capacity: 1
            time: 2
            unit: seconds
            initial-capacity: 1
            refill-speed: interval
  filters:
    - id: filter1
      cache-name: buckets
      url: .*
      rate-limits:
        - cache-key: getRemoteAddr()
          post-execute-condition: getStatus() eq 200
          bandwidths:
            - capacity: 10
              refill-capacity: 1
              time: 10
              unit: seconds
              initial-capacity: 5
              refill-speed: interval