import type { Metadata } from 'next';
import '@/app/globals.css';
import { Footer } from '@/components/footer';
import Header from '@/components/header';
import Sidebar from '@/components/sidebar';
import TableOfContents from '@/components/tableOfContents';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: '../../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pageHeadings: { id: string; text: string; level: number }[] = [];

  return (
    <html lang="en">
      <body className={`grid h-screen grid-rows-[auto_1fr_auto] ${pretendard.className}`}>
        <Header />
        <div className="grid grid-cols-[auto_minmax(auto,_1200px)_auto]">
          <Sidebar />
          <main className="mx-auto w-full max-w-4xl overflow-auto p-4">
            <div className="flex-grow p-4">{children}</div>
          </main>
          <TableOfContents headings={pageHeadings}></TableOfContents>
        </div>
        <Footer />
      </body>
    </html>
  );
}
