apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-backend-api
data:
  SPRING_PROFILES_ACTIVE: "dev"
  APP_CORS_ALLOWED_ORIGINS: "https://dev.contentria.com"
  APP_AUTH_OIDC_SUCCESS_REDIRECT_URL: "https://dev.contentria.com/login/callback"
  APP_AUTH_RECAPTCHA_EXPECTED_HOSTNAME: "dev.contentria.com"
