import type { Metadata } from 'next';
import '@/app/globals.css';
import localFont from 'next/font/local';

const pretendard = localFont({
  src: '../../../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className}`}>
        <main className="min-h-screen bg-gray-50">{children}</main>
      </body>
    </html>
  );
}
