apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: blog

patches:
  - path: configmap-patch.yaml

images:
  - name: contentria/blog-batch
    newTag: "1.1"
